### ISSUE TITLE
Duplicated "fix all auto-fixable tslint failures"

### ISSUE THREAD

**Issue by DanTup** [microsoft/typescript-tslint-plugin#47]
The first and fourth fixes here appear to be the same. I'm not sure if it's something I've done, or a bug (or how to tell).

<img width="634" alt="screenshot 2019-01-03 at 6 48 44 pm" src="https://user-images.githubusercontent.com/1078012/50655500-522a8d00-0f88-11e9-8ef9-fb893aceff05.png">

**Comment by mjbvz** [comment]
Difficult to fix because of how VS code gets quick fixes from the TS Server: we request fixes for each diagnostic in the selection. The plugin has no way to know that multiple requests are connected.

Could use https://github.com/Microsoft/TypeScript/issues/29452 or may need another TS Server api change (or maybe an ugly workaround)

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
